name: flutter_touch_spin
description: Simple number input spinner Widget for Flutter. Inspired by Bootstrap Touchspin
version: 2.0.0+k1
homepage: https://github.com/danvick/flutter_touch_spin
publish_to: none

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
