name: flutter_touch_spin
description: Simple number input spinner Widget for Flutter. Inspired by Bootstrap Touchspin
version: 2.0.0
homepage: https://github.com/danvick/flutter_touch_spin

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl:
    git: https://github.com/dart-lang/intl.git

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
